# Diffrent ways of creating Numpy arrays:

In [3]:
import numpy as np

In [2]:
var_1=np.array([1,2,3,4])
print(var_1)

[1 2 3 4]


In [5]:
var_2=np.array([[1,2,3],[4,5,6]])
print(var_2)

[[1 2 3]
 [4 5 6]]


In [10]:
#array of zero:

z=np.zeros((2,3))
z

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
#array od ones:

x=np.ones((4,4))
x

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [28]:
#array of random elements:
np.random.seed(4)
random=np.random.rand(4,4)
random

array([[0.96702984, 0.54723225, 0.97268436, 0.71481599],
       [0.69772882, 0.2160895 , 0.97627445, 0.00623026],
       [0.25298236, 0.43479153, 0.77938292, 0.19768507],
       [0.86299324, 0.98340068, 0.16384224, 0.59733394]])

In [26]:
np.random.seed(4)
np.random.randn(4,4)

array([[ 0.05056171,  0.49995133, -0.99590893,  0.69359851],
       [-0.41830152, -1.58457724, -0.64770677,  0.59857517],
       [ 0.33225003, -1.14747663,  0.61866969, -0.08798693],
       [ 0.4250724 ,  0.33225315, -1.15681626,  0.35099715]])

In [5]:
np.random.seed(4)
x_1=np.random.randint(low=50,high=100,size=(4,4))

# Slicing and Indexing:

In [6]:
x_1

array([[96, 55, 51, 90],
       [73, 58, 59, 89],
       [95, 80, 90, 86],
       [94, 88, 92, 53]])

In [7]:
x_1[1,1]

58

In [8]:
x_1[3,0]

94

In [9]:
x_1[0:2,0:2]

array([[96, 55],
       [73, 58]])

In [10]:
x_1[2:3,2:]

array([[90, 86]])

# Manipulation of array

In [13]:
#creation of identity matrix

np.identity(3,dtype="int")

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [15]:
b=np.arange(1,13).reshape(3,4)
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [18]:
b=b.ravel()
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [21]:
c=np.arange(1,13).reshape(4,3)
c

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [23]:
c.transpose()

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

# Stacking and Spliting of a matrix  

In [24]:
mat_1=np.arange(12).reshape(3,4)
mat_2=np.arange(12,24).reshape(3,4)

In [25]:
mat_1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [26]:
mat_2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [29]:
v=np.vstack((mat_1,mat_2))
v

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [30]:
h=np.hstack((mat_1,mat_2))
h

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [31]:
np.hsplit(v,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13],
        [16, 17],
        [20, 21]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15],
        [18, 19],
        [22, 23]])]

In [33]:
np.vsplit(h,3)

[array([[ 0,  1,  2,  3, 12, 13, 14, 15]]),
 array([[ 4,  5,  6,  7, 16, 17, 18, 19]]),
 array([[ 8,  9, 10, 11, 20, 21, 22, 23]])]