In [ ]:
NumPy----> Numerical Python

---> Array---> An array is the ordered data structure that contains data of similar type.

In [1]:
import numpy as np

In [2]:
array_1=np.array([1,2,3])
print(array_1)

[1 2 3]


In [4]:
array_2=np.array((20,30,40))
print(array_2)

[20 30 40]


In [8]:
array_3=np.array([[10,20,30],[40,50,60]])
print(array_3)

[[10 20 30]
 [40 50 60]]


In [9]:
np.array([1,2,3,4],dtype="complex")

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

In [11]:
np.array([1,2,3,4],dtype="float")

array([1., 2., 3., 4.])

In [12]:
list_1=[10,20,30,40]
print(list_1)

[10, 20, 30, 40]


# What is the major diffrence between numpy array and the python lists:

In [13]:
array_1

array([1, 2, 3])

In [15]:
array_2

array([20, 30, 40])

In [16]:
print(array_1+array_2)

[21 32 43]


In [17]:
list_1=[1,2,3]
list_2=[4,5,6]
print(list_1+list_2)

[1, 2, 3, 4, 5, 6]


In [19]:
list_ans=[]
for i,j in zip(list_1,list_2):
    list_ans.append(i+j)
print(list_ans)

[5, 7, 9]


In [22]:
#how to check the dimension of the array
array_1.ndim

1

In [23]:
array_3.ndim

2

In [24]:
#how we can check the shape of the matrix:
array_1.shape

(3,)

In [25]:
array_3.shape

(2, 3)

In [26]:
#How we can check the size of the array:
array_1.size

3

In [27]:
array_3.size

6

# Array Attributes:

In [29]:
a1=np.arange(10)    #only creat 1D array
print(a1)

[0 1 2 3 4 5 6 7 8 9]


In [31]:
a2=np.arange(12,dtype="float").reshape(4,3)
print(a2)

[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]


In [32]:
a2.astype(np.int64)#changing Dtype of array

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]], dtype=int64)

In [33]:
a2*4

array([[ 0.,  4.,  8.],
       [12., 16., 20.],
       [24., 28., 32.],
       [36., 40., 44.]])

In [34]:
for i in a2:
    print(i)

[0. 1. 2.]
[3. 4. 5.]
[6. 7. 8.]
[ 9. 10. 11.]


In [35]:
for i in np.nditer(a2):
    print(i)

0.0
1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0
11.0


In [36]:
a2>5

array([[False, False, False],
       [False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])